Dom manipulation
ConnecMent/inception pull request #78
Opened 2023-12-09 21:11 UTC by MahtaMirzaei

Closes: #54

2023-12-13 15:02 UTC, Mr-MRF-Dev requested changes

2023-12-13 15:02 UTC, Mr-MRF-Dev commented on mahta/JS/JS DOM-manipulation/script.js
> +    elm[index] = document.createElement("div");
rewrite the code without using the index parameter.

2023-12-13 17:39 UTC, MahtaMirzaei commented on mahta/JS/JS DOM-manipulation/script.js
> +  });
it were supposed to generate yellow random color for a subtree and generate  blue random color for f subtree, and it failed.

2023-12-16 12:42 UTC, Mr-MRF-Dev requested changes

2023-12-16 12:42 UTC, Mr-MRF-Dev commented on mahta/JS/JS DOM-manipulation/script.js
> +}
It's okay. Additionally, you can use the `HSL` Color Code to generate a random color.

2023-12-16 12:42 UTC, Mr-MRF-Dev commented on mahta/JS/JS DOM-manipulation/script.js
> +
To save divs in an object, use this syntax:

```js 
const allDivs = {};

  const divName = ["a", "b", "c", "d", "e", "g", "f", "h"];

  divName.forEach((name) => {
    allDivs[name] = document.createElement("div");
  });

```

2023-12-20 17:47 UTC, Mr-MRF-Dev requested changes

2023-12-20 17:47 UTC, Mr-MRF-Dev commented on mahta/JS/JS DOM-manipulation/script.js
> +  divElements["C"].appendChild(divElements["d"]);
`C` or `c` ???

2023-12-20 17:47 UTC, Mr-MRF-Dev commented on mahta/JS/JS DOM-manipulation/script.js
> +  divElements["C"].classList.add("container");
`C` or `c` ???

2023-12-20 17:47 UTC, Mr-MRF-Dev commented on mahta/JS/JS DOM-manipulation/script.js
> +    if ((Array.from(divElements["f"].childNodes).includes(x))||(Array.from(divElements[6].childNodes).includes(x)) ){
divElements[`6`] ???

2023-12-20 17:47 UTC, Mr-MRF-Dev commented on mahta/JS/JS DOM-manipulation/script.js
> +
Where is the reset ID for a button defined?

2023-12-20 17:47 UTC, Mr-MRF-Dev commented on mahta/JS/JS DOM-manipulation/script.js
> +  document.body.appendChild(buttonTag);
When you click the button, you should use DOM to change color or delete without resetting the page and creating new elements!

2023-12-20 17:47 UTC, Mr-MRF-Dev commented on mahta/JS/JS DOM-manipulation/script.js
> +  const divElements = {};
Please make the variable a global variable.

2023-12-29 13:11 UTC, Mr-MRF-Dev requested changes

2023-12-29 13:11 UTC, Mr-MRF-Dev commented on mahta/JS/JS DOM-manipulation/script.js
> +  dif();
It is not necessary to create a new node to change an element. Instead, follow the syntax to modify your elements.

```js
 // document.body.innerHTML = "";
  const buttonTag = document.getElementsByTagName("button")[0];
  buttonTag.textContent = "Reset";
  buttonTag.addEventListener("click", firstPage);
  // document.body.appendChild(buttonTag);
  Object.keys(elm).forEach((element) => {
   // elm[element] = document.createElement("div");
    const noode = document.createTextNode(element);
    elm[element].appendChild(noode);
  });
  // firstState();
  dif();

```

2023-12-29 14:49 UTC, Mr-MRF-Dev submitted a review, later dismissed

2023-12-29 14:50 UTC, Mr-MRF-Dev approved these changes

2023-12-29 18:45 UTC, Mr-MRF-Dev approved these changes

2023-12-29 18:50 UTC, Mr-MRF-Dev submitted a review, later dismissed

2023-12-29 18:53 UTC, Mr-MRF-Dev submitted a review, later dismissed
🌾

2023-12-30 11:15 UTC, mkermani144 requested changes
Many irrelevant changes are present in your PR. Please fix and request a review again.

2023-12-30 18:32 UTC, closed without merging